[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed0]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed1]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed2]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed3]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed4]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed5]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed6]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed7]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed8]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed9]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed10]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed11]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed12]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed13]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed14]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed15]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed16]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed17]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed18]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed19]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed20]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed21]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=160
Shape=Rectangle 0,0,(18*0.3),(-(160-(18*0.3))*[MeasureAudioSmoothed22]-(18*0.3)),((18*0.3)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1